config/routes.rb
Rails.application.routes.draw do
  
  resources :items, except: [:new , :create] do
    member do
      get 'add'
      get 'sell'
    end
  end

  resources :employees do 
    resource :employee_detail
  end

  devise_for :users

  root 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_one :employee_detail
end

app/models/employee_detail.rb
class EmployeeDetail < ActiveRecord::Base
  belongs_to :employee
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employee_details_controller.rb
class EmployeeDetailsController < ApplicationController
  before_filter :set_employee
  before_action :set_employee_detail, only: [:show, :edit, :update, :destroy]

  def set_employee
    @employee = Employee.find(params[:employee_id])
  end

  # GET /employee_details
  # GET /employee_details.json
  def index
    @employee_details = EmployeeDetail.all
  end

  # GET /employee_details/1
  # GET /employee_details/1.json
  def show
  end

  # GET /employee_details/new
  def new
    @employee_detail = EmployeeDetail.new
  end

  # GET /employee_details/1/edit
  def edit
  end

  # POST /employee_details
  # POST /employee_details.json
  def create

    @employee_detail = @employee.build_employee_detail(employee_detail_params)

    respond_to do |format|
      if @employee_detail.save
        format.html { redirect_to employee_employee_detail_path(@employee), notice: 'Employee detail was successfully created.' }
        format.json { render :show, status: :created, location: employee_employee_detail_path(@employee) }
      else
        format.html { render :new }
        format.json { render json: @employee_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_details/1
  # PATCH/PUT /employee_details/1.json
  def update
    respond_to do |format|
      if @employee_detail.update(employee_detail_params)
        format.html { redirect_to employee_employee_detail_path(@employee) , notice: 'Employee detail was successfully updated.' }
        format.json { render :show, status: :ok, location: employee_employee_detail_path(@employee)  }
      else
        format.html { render :edit }
        format.json { render json: @employee_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_details/1
  # DELETE /employee_details/1.json
  def destroy
    @employee_detail.destroy
    respond_to do |format|
      format.html { redirect_to @employee, notice: 'Employee detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_detail
      @employee_detail = @employee.employee_detail
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_detail_params
      params.require(:employee_detail).permit(:city, :address, :house_number, :phone_number, :postal_code, :employee_id)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all.order(surname: :asc)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "pracownicy"
      end
    end
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :surname, :workplace, :years_of_work, :access_to_cash)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def add
    item = Item.find_by_id(params[:id])

    if item
      item.quantity += 1
      item.save
    end

    redirect_to item
  end

  def sell
    @item = Item.find_by_id(params[:id])
    person = params[:person]
    items_quantity = params[:product][:quantity].to_i

    @invoice = Invoice.new(
        client_name: person[:name],
        client_surname: person[:surname],
        client_address: person[:address],
        item_id: @item.id,
        quantity: items_quantity
      )

    if @item and @item.quantity >= items_quantity
      @item.quantity -= items_quantity
      @item.save
      @invoice.save

      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "faktura"
        end
      end
    else
      redirect_to @item
    end

  end

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :quantity, :vat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_details_helper.rb
module EmployeeDetailsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/employee_details/_form.html.erb
<%= form_for(@employee_detail, url: employee_employee_detail_path(@employee)) do |f| %>
  <% if @employee_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee_detail.errors.count, "error") %> prohibited this employee_detail from being saved:</h2>

      <ul>
      <% @employee_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :house_number %><br>
    <%= f.number_field :house_number %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_details/edit.html.erb
<h1>Editing Employee Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee_detail %> |
<%= link_to 'Back', employee_details_path %>

app/views/employee_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employee Details</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Address</th>
      <th>House number</th>
      <th>Phone number</th>
      <th>Postal code</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_details.each do |employee_detail| %>
      <tr>
        <td><%= employee_detail.city %></td>
        <td><%= employee_detail.address %></td>
        <td><%= employee_detail.house_number %></td>
        <td><%= employee_detail.phone_number %></td>
        <td><%= employee_detail.postal_code %></td>
        <td><%= employee_detail.employee %></td>
        <td><%= link_to 'Show', employee_detail %></td>
        <td><%= link_to 'Edit', edit_employee_detail_path(employee_detail) %></td>
        <td><%= link_to 'Destroy', employee_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee detail', new_employee_detail_path %>

app/views/employee_details/new.html.erb
<h1>New Employee Detail</h1>

<%= render 'form' %>

app/views/employee_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @employee_detail.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee_detail.address %>
</p>

<p>
  <strong>House number:</strong>
  <%= @employee_detail.house_number %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @employee_detail.phone_number %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @employee_detail.postal_code %>
</p>


<%= link_to 'Edit', edit_employee_employee_detail_path(@employee_detail) %> | 
<%= link_to 'Back', @employee %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :workplace %><br>
    <%= f.text_field :workplace %>
  </div>
  <div class="field">
    <%= f.label :years_of_work %><br>
    <%= f.number_field :years_of_work %>
  </div>
  <div class="field">
    <%= f.label :access_to_cash %><br>
    <%= f.check_box :access_to_cash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Edycja Pracownika</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pracownicy</h1>

<table>
  <thead>
    <tr>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Miejsce Pracy</th>
      <th>Lata Pracy</th>
      <th>Dostęp do kasy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.surname %></td>
        <td><%= employee.workplace %></td>
        <td><%= employee.years_of_work %></td>
        <td><%= employee.access_to_cash %></td>
        <td><%= link_to 'Pokaż', employee,class: "btn btn-info" %></td>
        <td><%= link_to 'Edytuj', edit_employee_path(employee),class: "btn btn-warning" %></td>
        <td><%= link_to 'Usuń', employee, 
        method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path, class: "btn btn-info" %>

<br>
  <%= link_to "Magazyn", items_path, class: "btn btn-primary" %>

app/views/employees/new.html.erb
<h1>Nowy Pracownik</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<br>

<p id="notice"><%= notice %></p>

<p>
  <strong>Imie:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @employee.surname %>
</p>

<p>
  <strong>Workplace:</strong>
  <%= @employee.workplace %>
</p>

<p>
  <strong>Years of work:</strong>
  <%= @employee.years_of_work %>
</p>

<p>
  <strong>Access to cash:</strong>
  <%= @employee.access_to_cash %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'My employees', employees_path %> |


<% if @employee.employee_detail.nil? %>
  <%= link_to 'Dodaj dane pracownika',new_employee_employee_detail_path(@employee) %>
<% else %>
  <%= link_to 'Pokaż dane', employee_employee_detail_path(@employee) %>
<% end %>

app/views/employees/show.pdf.erb
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <h1>
            <a href="https://twitter.com/tahirtaous">
            <img src="logo.png">
            Logo here
            </a>
          </h1>
        </div>
        <div class="col-xs-6 text-right">
          <h1>INVOICE</h1>
          <h1><small>Invoice #001</small></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>From: <a href="#">Your Name</a></h4>
            </div>
            <div class="panel-body">
              <p>
                Address <br>
                details <br>
                more <br>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-5 col-xs-offset-2 text-right">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>To : <a href="#">Client Name</a></h4>
            </div>
            <div class="panel-body">
              <p>
                Address <br>
                details <br>
                more <br>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- / end client details section -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>
              <h4>Service</h4>
            </th>
            <th>
              <h4>Description</h4>
            </th>
            <th>
              <h4>Hrs/Qty</h4>
            </th>
            <th>
              <h4>Rate/Price</h4>
            </th>
            <th>
              <h4>Sub Total</h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Article</td>
            <td><a href="#">Title of your article here</a></td>
            <td class="text-right">-</td>
            <td class="text-right">$200.00</td>
            <td class="text-right">$200.00</td>
          </tr>
          <tr>
            <td>Template Design</td>
            <td><a href="#">Details of project here</a></td>
            <td class="text-right">10</td>
            <td class="text-right">75.00</td>
            <td class="text-right">$750.00</td>
          </tr>
          <tr>
            <td>Development</td>
            <td><a href="#">WordPress Blogging theme</a></td>
            <td class="text-right">5</td>
            <td class="text-right">50.00</td>
            <td class="text-right">$250.00</td>
          </tr>
        </tbody>
      </table>
      <div class="row text-right">
        <div class="col-xs-2 col-xs-offset-8">
          <p>
            <strong>
            Sub Total : <br>
            TAX : <br>
            Total : <br>
            </strong>
          </p>
        </div>
        <div class="col-xs-2">
          <strong>
          $1200.00 <br>
          N/A <br>
          $1200.00 <br>
          </strong>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h4>Bank details</h4>
            </div>
            <div class="panel-body">
              <p>Your Name</p>
              <p>Bank Name</p>
              <p>SWIFT : --------</p>
              <p>Account Number : --------</p>
              <p>IBAN : --------</p>
            </div>
          </div>
        </div>
        <div class="col-xs-7">
          <div class="span7">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4>Contact Details</h4>
              </div>
              <div class="panel-body">
                <p>
                  Email : you@example.com <br><br>
                  Mobile : -------- <br> <br>
                  Twitter : <a href="https://twitter.com/tahirtaous">@TahirTaous</a>
                </p>
                <h4>Payment should be made by Bank Transfer</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :vat %><br>
    <%= f.text_field :vat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="text-center">
  <%= link_to "Lista pracownikow", employees_path, class: "btn btn-primary btn-lg" %>
</div>

<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Vat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.vat %>%</td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/sell.html.erb
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1>Faktura nr. #<%= @invoice.id %></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>OD: Kuba Kołos</h4>
            </div>
            <div class="panel-body">
              <p>
                Address: Krakow <br>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-5 col-xs-offset-2 text-right">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>Do : <a href="#"><%= @invoice.client_name + " " + @invoice.client_surname %></a></h4>
            </div>
            <div class="panel-body">
              <p>
                Address: <%= @invoice.client_address %> <br>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- / end client details section -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>
              <h4>Nazwa Towaru</h4>
            </th>
            <th>
              <h4>Ilosc</h4>
            </th>
            <th>
              <h4>Cena</h4>
            </th>
            <th>
              <h4>Suma</h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @item.name %></td>
            <td><%= @invoice.quantity %></td>
            <td><%= @item.price %></td>
            <td><%= @item.price * @invoice.quantity %></td>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <div class="col-xs-5">
            <h4>Total: <%= @item.price * @invoice.quantity %> zł</h4> 
            <h4>TAX: <%= @item.vat %> %</h4> 
            <h4>Total: <%= (@item.price * @invoice.quantity - @item.price * @invoice.quantity * @item.vat).round(2) %> zł</h4>
          </p>
        </div>
      </div>

app/views/items/sell.pdf.erb
<h1>sakjdhkddasj</h1>

app/views/items/show.html.erb
<div class="col-md-4">
  <p id="notice"><%= notice %></p>

  <p>
    <h2>Nazwa: <%= @item.name %></h2>
  </p>

  <p>
    <h2>Ilość: <%= @item.quantity %></h2>
  </p>
  <p>
    <h2>Cena: <%= @item.price %> zł/szt</h2>
  </p>

  <p>
    <h2>VAT: <%= @item.vat %>%</h2>
  </p>

  <%= link_to 'Edytuj', edit_item_path(@item), class: "btn btn-warning" %> |
  <%= link_to 'Dodaj', add_item_path(@item), class: "btn btn-default" %>
</div>

<div class="col-md-3">
  <%= form_tag({controller: "items", action: "sell"}, method: "get", class: "form-group", format: :pdf) do %>
    <h2>Dane klienta:</h2>
    <%= label_tag("Imie:") %>
    <%= text_field(:person, :name, class: "form-control") %>
    <br>
    <%= label_tag("Nazwisko:") %>
    <%= text_field(:person, :surname, class: "form-control") %>
    <br>
    <%= label_tag("Adres:") %>
    <%= text_field(:person, :address, class: "form-control") %>
    <br>
    <%= label_tag("Ilośc sztuk do sprzedania:") %>
    <%= number_field(:product, :quantity, in: 1..100, class: "form-control") %>
    <br>
    <%= select_tag :format, options_for_select([["FAKTURA", "pdf"], ["HTML", "html"]], "pdf"), class: "form-control" %>
    <br>
    <%= submit_tag("Sprzedaj", class: "btn btn-success") %>
    <%= link_to 'Wróć', items_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="collapse navbar-collapse">
        
     
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li class="dropdown">
                  <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                    <i class="glyphicon glyphicon-user"></i> <%= current_user.email %> <span class="caret"></span></a>
                  <ul id="g-account-menu" class="dropdown-menu" role="menu">                    
                    <li><%= link_to destroy_user_session_path, :method => :delete do %>
                          <span class="glyphicon glyphicon-off"></span> Wyloguj
                        <% end %>
                    </li> 
                    <li>
                      <%= link_to edit_user_registration_path do %>
                          <span class="glyphicon glyphicon-cog"></span> Zmień hasło
                      <% end %>
                    </li> 
                  </ul>
                </li>
            <% else %>
              <li><%= link_to "Zaloguj się", new_user_session_path %></li> 
            <% end %>
          </ul>
        </div>

  <p class="alert"><%= alert %></p>




<%= yield %>

</body>
</html>

app/views/layouts/show.html.erb
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <h1>
            <a href="https://twitter.com/tahirtaous">
            <img src="logo.png">
            Logo here
            </a>
          </h1>
        </div>
        <div class="col-xs-6 text-right">
          <h1>INVOICE</h1>
          <h1><small>Invoice #001</small></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>From: <a href="#">Your Name</a></h4>
            </div>
            <div class="panel-body">
              <p>
                Address <br>
                details <br>
                more <br>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-5 col-xs-offset-2 text-right">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>To : <a href="#">Client Name</a></h4>
            </div>
            <div class="panel-body">
              <p>
                Address <br>
                details <br>
                more <br>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- / end client details section -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>
              <h4>Service</h4>
            </th>
            <th>
              <h4>Description</h4>
            </th>
            <th>
              <h4>Hrs/Qty</h4>
            </th>
            <th>
              <h4>Rate/Price</h4>
            </th>
            <th>
              <h4>Sub Total</h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Article</td>
            <td><a href="#">Title of your article here</a></td>
            <td class="text-right">-</td>
            <td class="text-right">$200.00</td>
            <td class="text-right">$200.00</td>
          </tr>
          <tr>
            <td>Template Design</td>
            <td><a href="#">Details of project here</a></td>
            <td class="text-right">10</td>
            <td class="text-right">75.00</td>
            <td class="text-right">$750.00</td>
          </tr>
          <tr>
            <td>Development</td>
            <td><a href="#">WordPress Blogging theme</a></td>
            <td class="text-right">5</td>
            <td class="text-right">50.00</td>
            <td class="text-right">$250.00</td>
          </tr>
        </tbody>
      </table>
      <div class="row text-right">
        <div class="col-xs-2 col-xs-offset-8">
          <p>
            <strong>
            Sub Total : <br>
            TAX : <br>
            Total : <br>
            </strong>
          </p>
        </div>
        <div class="col-xs-2">
          <strong>
          $1200.00 <br>
          N/A <br>
          $1200.00 <br>
          </strong>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h4>Bank details</h4>
            </div>
            <div class="panel-body">
              <p>Your Name</p>
              <p>Bank Name</p>
              <p>SWIFT : --------</p>
              <p>Account Number : --------</p>
              <p>IBAN : --------</p>
            </div>
          </div>
        </div>
        <div class="col-xs-7">
          <div class="span7">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4>Contact Details</h4>
              </div>
              <div class="panel-body">
                <p>
                  Email : you@example.com <br><br>
                  Mobile : -------- <br> <br>
                  Twitter : <a href="https://twitter.com/tahirtaous">@TahirTaous</a>
                </p>
                <h4>Payment should be made by Bank Transfer</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>